### ISSUE TITLE
Not compiling SASS in .vue files

### ISSUE THREAD

**Issue by itsgoofer** [vuejs-templates/browserify-simple#14]
I'm migrating an app from Vue 1.x to Vue 2.0.1. 
In the old app I had the following in the `vue.config.js`file:

```js
module.exports = {
  sass: {
  	includePaths: ['./src/sass'],
  	indentedSyntax: true
  }
}
```

So that in a .vue file I could write SASS using the indented syntax. 
However, in Vue 2.0.1, using any of the two Browserify templates, writing SASS in the style tag throws an error, and that led me to reformat all of my CSS in every component from the indented syntax to the normal SCSS syntax. 

In `component.vue`

```js
<template>
  <h3>Some Component</h3>
</template>


<script>
  export default {
    name: 'SomeComponent'		
  }
</script>


<style lang="sass">
  h3
    color: red
</style>
```

And the error is 
`VM416:27 Error: Invalid CSS after "": expected 1 selector or at-rule, was "h3" while parsing file: [filename]`

Is there a way to make it work?

Thanks in advance.

**Comment by itsgoofer** [comment]
Anyone?

**Comment by martinstarman** [comment]
Your styles looks like Stylus not Sass. It should be
```
<style lang="sass">
h3 {
    color: red;
}
</style>
```

**Comment by chrisvfritz** [comment]
`sass-loader` (confusingly) parses SCSS by default, causing this kind of error. `sassify` may do something similar.

**Comment by itsgoofer** [comment]
@martinstarman That's the indented syntax of a .sass file, which looks like stylus. It used to work with vuefy for version 1.x. 

@chrisvfritz Isn't there a way to make it work with indented syntax? I have a file called `vue.config.js`just like I had it in the vue 1.x project: 

```js
module.exports = {
  sass: {
  	includePaths: ['./src/sass'],
  	indentedSyntax: true
  }
}
```

**Comment by chrisvfritz** [comment]
Strange that it's not working with `indentedSyntax: true`. I don't use Browserify, but something similar is necessary (and works) for Webpack.

**Comment by itsgoofer** [comment]
Turns out I had to install node-sass, which surprisingly wasn't in my dev-dependencies list (and doesn't come with the cue-cli browserify template)
I've published a tutorial for those who hit the same wall:

http://omarfouad.com/blog/using-sass-indented-syntax-with-vueify-and-vuejs-2/

**Comment by designbyadrian** [comment]
@martinstarman your example is SCSS, not SASS
