### ISSUE TITLE
Initiating in current directory instructions

### ISSUE THREAD

**Issue by esganzerla** [vuejs-templates/browserify-simple#15]
Hi,

I wanted to make a PR for this, but I don't know how, if possible without modifying vue-cli.

Anyway, the problem is, it is showing:

```
 To get started:
   
 cd dir_name
```

Even when I initiate it in the current directory.

**Comment by LinusBorg** [comment]
That requires a change in vue-cli, since the information about weither we create in the current directoy is not passed to the code that actually creates this message.
