### ISSUE TITLE
'This' object inside vue instance methods is undefined

### ISSUE THREAD

**Issue by CaptainYouz** [vuejs-templates/browserify-simple#6]
Hi !

I have also tested on the browserify vuejs-templates and i have the same error.
I followed the README and have set up a new project using vue-cli browserify, but when i'm trying to reach the 'this' object inside vue instance method (created, beforeCompile...), it always return undefined into the console.

Here is an example when i modify the script part of the App.vue file (it's the only one that i modified). 

```
export default {
  data () {
    return {
      // note: changing this line won't causes changes
      // with hot-reload because the reloaded component
      // preserves its current state and we are modifying
      // its initial state.
      msg: 'Hello Vue!'
    }
  },
  created: () => {
    console.log('created', this);
  },
  beforeCompile: () => {
    console.log('beforeCompile', this);
  },
  compiled: () => {
    console.log('compiled', this);
  },
  ready: () => {
    console.log('ready', this);
  }
}
```

On each log, this is undefined.

<img width="1275" alt="screen shot 2016-04-23 at 1 44 37 pm" src="https://cloud.githubusercontent.com/assets/2973285/14761202/90361ce6-0959-11e6-9ecc-314c42dcadb4.png">

I'm am missing something ?

Configuration: Macbook Pro on Chrome v50.0.2661.75 (64-bit)

**Comment by chrisvfritz** [comment]
@CaptainYouz This happens because the ES6/2015 arrow function syntax (`() => {}`) binds `this` to the parent context. In this case, the parent context is the module. Since `this` is undefined in the module context, that undefined value is passed to each of the lifecycle methods instead of the view model as you'd expect.

To fix this, you'll need to use a normal function declaration:

``` js
created: function () {
  console.log('created', this);
},
```

_Or_, my personal preference is the ES6/2015 shorthand, which does the same as above:

``` js
created () {
  console.log('created', this);
},
```

**Comment by CaptainYouz** [comment]
Thanks for the explanation !
It's working now 👍 .

**Comment by jgb-solutions** [comment]
great!

**Comment by taoliujun** [comment]
but `this` is still link methods.but not vm.

**Comment by imageslr** [comment]
Thanks a lot!!!

**Comment by theluk** [comment]
how are you dealing with methods you need to bind to `this`. for example when you want to wrap a method in lodash´s debounce?

**Comment by chrisvfritz** [comment]
@theluk You don't need to do anything special. Just wrapping the function with debounce should work, e.g.:

``` js
myMethod: debounce(
  function () {
    // `this` is the app/component instance here
  },
  500
)
```
