### ISSUE TITLE
Template appears broken

### ISSUE THREAD

**Issue by tomcon** [vuejs-templates/browserify-simple#7]
Site loads but nothing displaying in browser

also this:
Error: Cannot find module 'vue-hot-reload-api' from ..

**Comment by yyx990803** [comment]
I assume you are using Node < 4.x? It should work properly in Node 5 and above.

**Comment by chrisvfritz** [comment]
@tomcon Just pinging on this. Did you try this with node 5+ and did it work? If not, can you post more information about your setup in [this issue for vueify](https://github.com/vuejs/vueify/issues/46)?

**Comment by tomcon** [comment]
@yyx990803 @chrisvfritz am using node v4.4.5 so ok I'll try v5 when I can
