### ISSUE TITLE
No matches found.

### ISSUE THREAD

**Issue by flyingearl** [vuejs-templates/browserify-simple#9]
I'm really sorry if this is a stupid question but when I try and run `vue init browserify-simple#1.0 my-project` it comes back saying "no matches found: browserify-simple#1.0". Is it me or is there something missing?

Thank you in advance.

**Comment by zigomir** [comment]
@flyingearl which `vue-cli` version do you have? Try running `vue version`. It should work with `2.2.0+`.

**Comment by chrisvfritz** [comment]
Closing due to lack of response.
